"""KnowledgeObject v1.0 envelope contract helpers.

Single home for the wrapper-contract logic so the kernel app, the
import/sync paths, the schema build script, and the federation layer all
enforce the same rules. The type catalog itself (``KO_TYPE_CATALOG`` /
``KO_BRANCHES``) stays in ``duecare.chat.app``; callers pass it in, which
keeps this module import-light (stdlib only) and usable from scripts
without booting FastAPI.

The envelope wrapper shape:

    {
      "schema_version": "1.0",
      "knowledge_object_type": "<leaf type>",
      "id": "kebab-case-id",
      "version": "v1",
      "provenance": {"created_at": ..., "created_by": "<node id>",
                      "content_sha256": "<hex>"},
      "content": {...type-specific...},
      "tags": [...],
      "extensions": {...}
    }
"""
from __future__ import annotations

import hashlib
import json
import os
import re
from typing import Any, Iterable, Mapping

ENVELOPE_SCHEMA_VERSION = "1.0"

_ID_RE = re.compile(r"^[a-z0-9][a-z0-9\-_]*$")


def node_id() -> str:
    """Stable identity this node stamps into provenance.created_by.

    Defaults to the historical ``kernel-01`` so single-node deployments
    are unchanged; federated deployments set ``DUECARE_NODE_ID``.
    """
    return os.environ.get("DUECARE_NODE_ID", "").strip() or "kernel-01"


def content_sha256(content: Mapping[str, Any]) -> str:
    """Canonical content hash: sha256 over sorted-key compact JSON."""
    body = json.dumps(content, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(body.encode("utf-8")).hexdigest()


def validate_envelope(
    env: Any,
    *,
    known_types: Iterable[str],
    catalog: Mapping[str, Mapping[str, Any]] | None = None,
) -> tuple[bool, str]:
    """Validate the envelope wrapper, plus per-type required content keys.

    ``catalog`` is the KO_TYPE_CATALOG mapping; when provided, the type's
    ``required_content_keys`` become binding (a missing key rejects the
    envelope) instead of advisory.
    """
    if not isinstance(env, dict):
        return False, "envelope must be a JSON object"
    if env.get("schema_version") != ENVELOPE_SCHEMA_VERSION:
        return False, f'schema_version must be "{ENVELOPE_SCHEMA_VERSION}"'
    ko_type = env.get("knowledge_object_type")
    types = set(known_types)
    if ko_type not in types:
        return False, f"knowledge_object_type must be one of {sorted(types)}"
    ko_id = env.get("id")
    if not isinstance(ko_id, str) or not ko_id.strip():
        return False, "`id` must be a non-empty string"
    if not _ID_RE.match(ko_id):
        return False, "`id` must be kebab-case (lowercase + digits + hyphen/underscore)"
    content = env.get("content")
    if not isinstance(content, dict):
        return False, "`content` must be a JSON object"
    if catalog:
        required = list((catalog.get(ko_type) or {}).get("required_content_keys") or [])
        missing = [k for k in required if k not in content]
        if missing:
            return False, (
                f"content for `{ko_type}` is missing required key(s): "
                f"{', '.join(missing)} (see /api/knowledge/type-catalog)"
            )
    return True, ""


def stamp_provenance(
    env: dict,
    *,
    created_at: str,
    created_by: str | None = None,
) -> dict:
    """Fill provenance defaults + recompute the content hash in place.

    ``content_sha256`` is always recomputed from the stored content so a
    recipient can verify the envelope was not modified after this stamp.
    """
    prov = env.setdefault("provenance", {})
    prov.setdefault("created_at", created_at)
    prov.setdefault("created_by", created_by or node_id())
    prov["content_sha256"] = content_sha256(env.get("content") or {})
    return prov


def build_envelope_json_schema(
    catalog: Mapping[str, Mapping[str, Any]],
    branches: Mapping[str, str],
) -> dict[str, Any]:
    """Generate the machine-enforceable JSON Schema (draft 2020-12).

    The wrapper shape is fixed; per-type required content keys come from
    the catalog via if/then clauses, so one artifact carries the whole
    contract. Regenerated by ``scripts/build_envelope_schema.py``.
    """
    type_clauses = []
    for ko_type in sorted(branches):
        required = list((catalog.get(ko_type) or {}).get("required_content_keys") or [])
        clause: dict[str, Any] = {
            "if": {"properties": {"knowledge_object_type": {"const": ko_type}}},
            "then": {"properties": {"content": {"required": required}}},
        }
        type_clauses.append(clause)
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://duecare-ai.com/static/envelope_schema.json",
        "title": "DueCare KnowledgeObject envelope",
        "description": (
            "Versioned envelope for anonymized, shareable knowledge objects. "
            "Wrapper fields are fixed; content keys are type-specific. "
            "provenance.content_sha256 is sha256 over sorted-key compact JSON "
            "of `content` and lets any recipient verify integrity."
        ),
        "type": "object",
        "required": ["schema_version", "knowledge_object_type", "id", "content"],
        "properties": {
            "schema_version": {"const": ENVELOPE_SCHEMA_VERSION},
            "knowledge_object_type": {"enum": sorted(branches)},
            "id": {"type": "string", "pattern": _ID_RE.pattern},
            "version": {"type": "string"},
            "provenance": {
                "type": "object",
                "properties": {
                    "created_at": {"type": "string"},
                    "created_by": {
                        "type": "string",
                        "description": "Originating node id (DUECARE_NODE_ID).",
                    },
                    "content_sha256": {
                        "type": "string",
                        "pattern": "^[0-9a-f]{64}$",
                    },
                    "vetted": {"type": "boolean"},
                    "served_at": {"type": "string"},
                },
            },
            "content": {"type": "object"},
            "tags": {"type": "array", "items": {"type": "string"}},
            "extensions": {"type": "object"},
        },
        "allOf": type_clauses,
        "x-branches": {t: b for t, b in sorted(branches.items())},
    }
