"""Prometheus metrics endpoint + counters used by the tenancy /
metering / ratelimit middleware.

Pure Python, no FastAPI dependencies — the middleware modules import
counters from here and FastAPI wires the /metrics route via
[`install_observability`][duecare.server.observability.install_observability].

Counters and histograms emitted (all use the `duecare_` prefix to
match the Grafana dashboard at
`infra/observability/grafana/dashboards/duecare-overview.json`):

  Counters:
    duecare_chat_requests_total{tenant, route, status}
    duecare_model_tokens_in_total{tenant, model}
    duecare_model_tokens_out_total{tenant, model}
    duecare_grep_rule_hits_total{rule_id, severity}
    duecare_rag_retrievals_total{corpus_id}
    duecare_tool_calls_total{tool_name, success}
    duecare_ilo_indicator_hits_total{indicator}
    duecare_corridor_lookups_total{corridor_code}
    duecare_rate_limit_rejections_total{tenant, reason}

  Histograms:
    duecare_chat_request_duration_seconds{tenant, model, harness_layer}

  Gauges:
    duecare_tenant_token_budget_daily{tenant}
    duecare_tenant_concurrency_in_flight{tenant}

Tenant labels are privacy-preserving stable hashes, not raw tenant IDs.
Set DUECARE_METRICS_TENANT_SALT in production to prevent offline guessing
of low-entropy tenant names.

If `prometheus-client` is not installed, all counters become no-ops
so the server still runs in lean / development environments.
"""
from __future__ import annotations

import hashlib
import hmac
import os
import secrets
from typing import Any

from starlette.requests import Request

try:
    from prometheus_client import (
        CollectorRegistry, Counter, Gauge, Histogram,
        CONTENT_TYPE_LATEST, generate_latest,
    )
    _PROM_AVAILABLE = True
except ImportError:                              # pragma: no cover
    _PROM_AVAILABLE = False
    CollectorRegistry = None                     # type: ignore
    Counter = Gauge = Histogram = None           # type: ignore
    CONTENT_TYPE_LATEST = "text/plain; version=0.0.4; charset=utf-8"

    def generate_latest(_registry: Any) -> bytes:  # type: ignore
        return b"# prometheus-client not installed; metrics disabled\n"


# Module-level registry so multiple middleware modules can share the
# same counters without re-registration. Tests can pass an explicit
# registry into create_app() if needed.
_REGISTRY = CollectorRegistry() if _PROM_AVAILABLE else None


class _NoopMetric:
    """Stand-in when prometheus-client is missing — silently drops calls."""
    def labels(self, **_: Any) -> "_NoopMetric": return self
    def inc(self, *_: Any, **__: Any) -> None: pass
    def dec(self, *_: Any, **__: Any) -> None: pass
    def observe(self, *_: Any, **__: Any) -> None: pass
    def set(self, *_: Any, **__: Any) -> None: pass


def tenant_metric_label(tenant: str) -> str:
    """Return a stable privacy-preserving Prometheus tenant label."""
    tenant_value = str(tenant or "public").strip() or "public"
    tenant_value = tenant_value[:1024]
    salt = os.environ.get("DUECARE_METRICS_TENANT_SALT", "").strip()
    secret = salt or os.environ.get("DUECARE_METRICS_TOKEN", "").strip()
    secret = secret or os.environ.get("DUECARE_API_TOKEN", "").strip()
    encoded_tenant = tenant_value.encode("utf-8", errors="ignore")
    if secret:
        digest = hmac.new(
            secret.encode("utf-8", errors="ignore"),
            encoded_tenant,
            hashlib.sha256,
        ).hexdigest()
    else:
        digest = hashlib.sha256(encoded_tenant).hexdigest()
    return f"tenant_{digest[:12]}"


def _counter(name: str, doc: str, labels: list[str]) -> Any:
    if not _PROM_AVAILABLE:
        return _NoopMetric()
    return Counter(name, doc, labels, registry=_REGISTRY)


def _gauge(name: str, doc: str, labels: list[str]) -> Any:
    if not _PROM_AVAILABLE:
        return _NoopMetric()
    return Gauge(name, doc, labels, registry=_REGISTRY)


def _histogram(name: str, doc: str, labels: list[str],
                buckets: tuple[float, ...]) -> Any:
    if not _PROM_AVAILABLE:
        return _NoopMetric()
    return Histogram(name, doc, labels, buckets=buckets, registry=_REGISTRY)


# ─── Counters ──────────────────────────────────────────────────────
chat_requests_total = _counter(
    "duecare_chat_requests_total",
    "Total chat requests by tenant + route + HTTP status.",
    ["tenant", "route", "status"],
)
model_tokens_in_total = _counter(
    "duecare_model_tokens_in_total",
    "Total model input tokens consumed by tenant + model.",
    ["tenant", "model"],
)
model_tokens_out_total = _counter(
    "duecare_model_tokens_out_total",
    "Total model output tokens generated by tenant + model.",
    ["tenant", "model"],
)
grep_rule_hits_total = _counter(
    "duecare_grep_rule_hits_total",
    "Total GREP-rule firings by rule_id + severity.",
    ["rule_id", "severity"],
)
rag_retrievals_total = _counter(
    "duecare_rag_retrievals_total",
    "Total RAG retrievals by corpus.",
    ["corpus_id"],
)
tool_calls_total = _counter(
    "duecare_tool_calls_total",
    "Total tool invocations by name + success flag.",
    ["tool_name", "success"],
)
ilo_indicator_hits_total = _counter(
    "duecare_ilo_indicator_hits_total",
    "Total ILO C029 indicator firings by indicator number 1-11.",
    ["indicator"],
)
corridor_lookups_total = _counter(
    "duecare_corridor_lookups_total",
    "Total migration-corridor lookups by corridor code.",
    ["corridor_code"],
)
rate_limit_rejections_total = _counter(
    "duecare_rate_limit_rejections_total",
    "Total requests rejected with HTTP 429 by tenant + reason.",
    ["tenant", "reason"],
)

# ─── Histograms ────────────────────────────────────────────────────
# Buckets are chosen to span the practical range for chat completions:
# 100ms (cheap canned response) to 60s (cold-start + large model).
chat_request_duration_seconds = _histogram(
    "duecare_chat_request_duration_seconds",
    "Wall-clock duration of a chat request, by tenant + model + layer.",
    ["tenant", "model", "harness_layer"],
    buckets=(0.1, 0.25, 0.5, 1, 2, 4, 8, 16, 32, 60, float("inf")),
)

# ─── Gauges ────────────────────────────────────────────────────────
tenant_token_budget_daily = _gauge(
    "duecare_tenant_token_budget_daily",
    "Daily output-token budget configured for each tenant. "
    "Drives the alert in infra/observability/prometheus/rules.yml.",
    ["tenant"],
)
tenant_concurrency_in_flight = _gauge(
    "duecare_tenant_concurrency_in_flight",
    "In-flight request count per tenant. Drives the per-tenant "
    "concurrency cap enforced in ratelimit.py.",
    ["tenant"],
)


def install_observability(app: Any) -> None:
    """Wire the /metrics endpoint into a FastAPI app.

    No-op when prometheus-client is missing — the route still exists
    and returns a one-line stub so health-check probes succeed.
    """
    from fastapi import Response

    @app.get("/metrics", include_in_schema=False)
    def metrics(request: Request) -> Response:
        metrics_token = os.environ.get("DUECARE_METRICS_TOKEN", "").strip()
        api_token = os.environ.get("DUECARE_API_TOKEN", "").strip()
        token = metrics_token or api_token
        if token:
            authorization = request.headers.get("authorization", "")
            if not secrets.compare_digest(authorization, f"Bearer {token}"):
                return Response(
                    content="unauthorized\n",
                    media_type="text/plain",
                    status_code=401,
                )
        return Response(
            content=generate_latest(_REGISTRY),
            media_type=CONTENT_TYPE_LATEST,
        )


# Public sym for tests to inspect the registry.
def registry() -> Any:
    return _REGISTRY
