{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "duecare.fullname" . }}
  labels:
    {{- include "duecare.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "duecare.fullname" $ }}-{{ .service }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
{{- if and .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "duecare.serviceAccountName" . }}
  labels:
    {{- include "duecare.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.secrets.hfToken -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "duecare.fullname" . }}-secrets
  labels:
    {{- include "duecare.labels" . | nindent 4 }}
type: Opaque
stringData:
  hf-token: {{ .Values.secrets.hfToken | quote }}
{{- end }}
