"""scripts/coverage_matrix.py

Generate a coverage matrix over the prompt corpus, showing how many
prompts exist for each (category x sector), (corridor x difficulty),
(category x ILO indicator), etc. -- so contributors can see at a glance
where the corpus is dense vs sparse and where new prompts would close
the biggest gaps.

Output goes to docs/corpus_coverage.md (markdown tables) and
docs/corpus_coverage.json (raw counts for downstream tools).

Usage
-----
    python scripts/coverage_matrix.py
    python scripts/coverage_matrix.py --output docs/corpus_coverage.md
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parent.parent
EXAMPLES = (
    REPO_ROOT
    / "packages"
    / "duecare-llm-chat"
    / "src"
    / "duecare"
    / "chat"
    / "harness"
    / "_examples.json"
)


def load_corpus() -> list[dict]:
    return json.loads(EXAMPLES.read_text(encoding="utf-8"))


def matrix_2d(
    rows_field: str,
    cols_field: str,
    corpus: list[dict],
    *,
    multi_value_cols: bool = False,
) -> tuple[list[str], list[str], dict[tuple[str, str], int]]:
    """Build a 2D count matrix indexed by (rows_field, cols_field).

    If `multi_value_cols=True`, the cols_field is treated as a list and each
    value contributes to its own column (used for ilo_indicators).
    """
    cell: Counter = Counter()
    for e in corpus:
        rv = e.get(rows_field) or "(none)"
        if multi_value_cols:
            cvs = e.get(cols_field) or []
            if not cvs:
                cvs = ["(none)"]
            for cv in cvs:
                cell[(str(rv), str(cv))] += 1
        else:
            cv = e.get(cols_field) or "(none)"
            cell[(str(rv), str(cv))] += 1
    rows = sorted({k[0] for k in cell})
    cols = sorted({k[1] for k in cell})
    return rows, cols, dict(cell)


def render_table(
    rows: list[str],
    cols: list[str],
    cell: dict[tuple[str, str], int],
    rows_label: str,
    cols_label: str,
    *,
    sort_by_total: bool = True,
) -> str:
    """Render a 2D matrix as a markdown table with row/column totals."""
    if sort_by_total:
        rows = sorted(rows, key=lambda r: -sum(cell.get((r, c), 0) for c in cols))
        cols = sorted(cols, key=lambda c: -sum(cell.get((r, c), 0) for r in rows))
    header = f"| {rows_label} \\ {cols_label} | " + " | ".join(cols) + " | **Σ** |"
    sep = "|---" * (len(cols) + 2) + "|"
    lines = [header, sep]
    col_totals = [0] * len(cols)
    for r in rows:
        row_vals = [cell.get((r, c), 0) for c in cols]
        for i, v in enumerate(row_vals):
            col_totals[i] += v
        cells = " | ".join(str(v) if v else "·" for v in row_vals)
        lines.append(f"| **{r}** | {cells} | **{sum(row_vals)}** |")
    lines.append(
        "| **Σ** | " + " | ".join(f"**{v}**" for v in col_totals)
        + f" | **{sum(col_totals)}** |"
    )
    return "\n".join(lines)


def find_gaps(
    rows: list[str],
    cols: list[str],
    cell: dict[tuple[str, str], int],
    threshold: int = 1,
    top_n: int = 20,
) -> list[tuple[str, str, int]]:
    """Return list of (row, col, count) cells with count below threshold,
    sorted by row+col total density (sparsest interesting cells first)."""
    row_totals = {r: sum(cell.get((r, c), 0) for c in cols) for r in rows}
    col_totals = {c: sum(cell.get((r, c), 0) for r in rows) for c in cols}
    gaps = []
    for r in rows:
        for c in cols:
            v = cell.get((r, c), 0)
            if v >= threshold:
                continue
            density = row_totals[r] + col_totals[c]
            gaps.append((r, c, v, density))
    gaps.sort(key=lambda x: -x[3])
    return [(r, c, v) for r, c, v, _ in gaps[:top_n]]


def write_outputs(corpus: list[dict], md_path: Path, json_path: Path) -> None:
    sections = [
        "# Prompt Corpus Coverage Matrix",
        "",
        f"**Total prompts:** {len(corpus)}",
        "",
        "Auto-generated by `scripts/coverage_matrix.py`. Each section is a 2D "
        "table of prompt counts across two dimensions of the corpus. A `·` "
        "marks an empty cell (no prompts). Use this view to identify where "
        "to focus new prompt contributions -- empty cells in a high-density "
        "row/column are the highest-value gaps.",
        "",
        "## Section 1 — Category × Sector",
        "",
    ]
    rows, cols, cell = matrix_2d("category", "sector", corpus)
    sections.append(render_table(rows, cols, cell, "Category", "Sector"))
    cat_sec = {"rows": rows, "cols": cols,
               "cells": {f"{r}|{c}": v for (r, c), v in cell.items()}}

    sections += ["", "## Section 2 — Category × Corridor", ""]
    rows, cols, cell = matrix_2d("category", "corridor", corpus)
    sections.append(render_table(rows, cols, cell, "Category", "Corridor"))
    cat_corr = {"rows": rows, "cols": cols,
                "cells": {f"{r}|{c}": v for (r, c), v in cell.items()}}

    sections += ["", "## Section 3 — Category × Difficulty", ""]
    rows, cols, cell = matrix_2d("category", "difficulty", corpus)
    sections.append(render_table(rows, cols, cell, "Category", "Difficulty"))
    cat_diff = {"rows": rows, "cols": cols,
                "cells": {f"{r}|{c}": v for (r, c), v in cell.items()}}

    sections += ["", "## Section 4 — Sector × Corridor", ""]
    rows, cols, cell = matrix_2d("sector", "corridor", corpus)
    sections.append(render_table(rows, cols, cell, "Sector", "Corridor"))
    sec_corr = {"rows": rows, "cols": cols,
                "cells": {f"{r}|{c}": v for (r, c), v in cell.items()}}

    sections += ["", "## Section 5 — Category × ILO Indicator", ""]
    rows, cols, cell = matrix_2d("category", "ilo_indicators", corpus,
                                  multi_value_cols=True)
    sections.append(render_table(rows, cols, cell, "Category", "ILO Indicator"))
    cat_ilo = {"rows": rows, "cols": cols,
               "cells": {f"{r}|{c}": v for (r, c), v in cell.items()}}

    # --- Top gaps ---
    sections += [
        "",
        "## High-priority gaps (low coverage in dense rows / columns)",
        "",
        "Empty cells in the (Category × Sector) matrix that sit in dense rows or "
        "columns -- the strongest signal of where a contributor could close a real gap.",
        "",
        "| # | Category | Sector | Count |",
        "|---|---|---|---|",
    ]
    rows, cols, cell = matrix_2d("category", "sector", corpus)
    gaps = find_gaps(rows, cols, cell, threshold=1, top_n=20)
    for i, (r, c, v) in enumerate(gaps, 1):
        sections.append(f"| {i} | {r} | {c} | {v} |")

    sections += [
        "",
        "Empty (Category × Corridor) cells:",
        "",
        "| # | Category | Corridor | Count |",
        "|---|---|---|---|",
    ]
    rows, cols, cell = matrix_2d("category", "corridor", corpus)
    gaps = find_gaps(rows, cols, cell, threshold=1, top_n=20)
    for i, (r, c, v) in enumerate(gaps, 1):
        sections.append(f"| {i} | {r} | {c} | {v} |")

    sections += [
        "",
        "## Reproduce",
        "",
        "```bash",
        "python scripts/coverage_matrix.py",
        "```",
        "",
    ]

    md_path.write_text("\n".join(sections) + "\n", encoding="utf-8")
    print(f"[coverage_matrix] wrote {md_path} "
          f"({md_path.stat().st_size:,} bytes)")

    json_path.write_text(
        json.dumps(
            {
                "n_prompts": len(corpus),
                "category_x_sector": cat_sec,
                "category_x_corridor": cat_corr,
                "category_x_difficulty": cat_diff,
                "sector_x_corridor": sec_corr,
                "category_x_ilo_indicator": cat_ilo,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    print(f"[coverage_matrix] wrote {json_path}")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--output",
        type=Path,
        default=REPO_ROOT / "docs" / "corpus_coverage.md",
    )
    p.add_argument(
        "--json-output",
        type=Path,
        default=REPO_ROOT / "docs" / "corpus_coverage.json",
    )
    args = p.parse_args()
    corpus = load_corpus()
    print(f"[coverage_matrix] loaded {len(corpus)} prompts")
    write_outputs(corpus, args.output, args.json_output)


if __name__ == "__main__":
    main()
