"""Generate structured-post JSON corpus for the data_intelligence
bucket (v0.12.0).

Each post is a machine-readable representation of a recruitment-style
social-media post / DM / channel message, paired with ground-truth
trafficking-indicator labels. Designed for:

  - Analyst-style queries that ingest structured data rather than
    OCR'd screenshots.
  - Cross-platform aggregation (FB + TikTok + Telegram + Instagram
    + Discord + X + WhatsApp + SMS posts queryable together).
  - Regulator-audit prompts that mirror what a platform would
    surface in an enforcement-request response.
  - Fine-tune training data with structured (post → indicators)
    pairs.

All entries CC0-1.0 with mandatory synthetic disclaimer.

Run:  py -3.10 scripts/generate_synthetic_posts.py
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

OUT_DIR = Path("packages/duecare-llm-chat/src/duecare/chat/static/synthetic/posts")
OUT_DIR.mkdir(parents=True, exist_ok=True)
GEN_VERSION = "duecare-synthetic-posts/0.12.0"

DISCLAIMER = (
    "All persons, agencies, handles, engagement counts, timestamps, "
    "and contact details in this post-record are FICTIONAL. Composite "
    "character names + reserved-for-fictional-use handle prefixes "
    "(@..._composite, @synth_...) make the synthetic nature visually "
    "unambiguous. Generated by deterministic Python templating, not "
    "scraped from real accounts. CC0 / public-domain dedication. "
    "Not real evidence; not for use in legal, journalistic, or "
    "investigative proceedings.")


def _record(post_id: str, *, platform: str, captured_at: str,
              author: dict, text: str, language: str = "en",
              media: list = None, engagement: dict = None,
              platform_signals: dict = None,
              trafficking_indicators: list = None) -> dict:
    return {
        "post_id":     post_id,
        "platform":    platform,
        "captured_at": captured_at,
        "author":      author,
        "text":        text,
        "language":    language,
        "media":       media or [],
        "engagement":  engagement or {},
        "platform_signals": platform_signals or {},
        "trafficking_indicators_present": trafficking_indicators or [],
        "synthetic":   True,
        "license":     "CC0-1.0",
        "synthetic_disclaimer": DISCLAIMER,
        "intended_use": "Educational — trafficking-pattern recognition for AI safety harness",
        "generator":   GEN_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }


def _write(record: dict) -> None:
    out = OUT_DIR / f"{record['platform']}_{record['post_id']}.json"
    out.write_text(json.dumps(record, indent=2, ensure_ascii=False) + "\n",
                       encoding="utf-8")


def main() -> None:
    records = [
        # ── Facebook recruitment posts ──────────────────────────
        _record(
            "fb_001", platform="facebook",
            captured_at="2026-04-15T10:14:00Z",
            author={"name": "ABC Manpower Inc. (composite)",
                    "handle": "@abc_manpower_composite",
                    "verified": False,
                    "account_age_days": 47,
                    "follower_count": 8421,
                    "synthetic": True},
            text="URGENT! 30 Filipina maids for Saudi Arabia 🇸🇦. "
                 "Free flight, free visa, only PHP 50,000 training "
                 "fee, salary SAR 1,800/month. 2-year contract. "
                 "WhatsApp +63 555-0001-1234 now. First-come "
                 "first-served! No POEA test required, we handle "
                 "everything!",
            media=[{"type": "image",
                    "url": "/static/synthetic/fb_post_ph_hk_urgent.png",
                    "alt": "Synthetic Facebook ad screenshot"}],
            engagement={"likes": 847, "comments": 92, "shares": 128, "views": None},
            platform_signals={"is_sponsored": True,
                              "comments_disabled": False,
                              "has_external_link": True,
                              "external_link_domain": "wa.me",
                              "post_creation_velocity_24h": 47},
            trafficking_indicators=[
                "fee_camouflage", "off_platform_redirection",
                "urgency_pressure", "first_come_first_served",
                "POEA_test_bypass_claim"]),
        _record(
            "fb_002", platform="facebook",
            captured_at="2026-04-22T08:33:00Z",
            author={"name": "PT Alpha Bravo Recruitment (composite)",
                    "handle": "@alpha_bravo_synth",
                    "verified": False,
                    "account_age_days": 122,
                    "follower_count": 24105,
                    "synthetic": True},
            text="🌟 Looking for hard-working Indonesian sisters! 🌟\n\n"
                 "Riyadh family seeks experienced housekeeper. Salary "
                 "IDR 4 juta + free housing + food. Contract 2 years, "
                 "advance fee IDR 25 juta (deductable from salary).\n\n"
                 "DM only — no calls. Limited slots!",
            language="id",
            media=[{"type": "image",
                    "url": "/static/synthetic/fb_post_id_sa_modern.png",
                    "alt": "Synthetic Indonesian-Saudi recruitment ad"}],
            engagement={"likes": 1230, "comments": 156, "shares": 89, "views": None},
            platform_signals={"is_sponsored": False,
                              "comments_disabled": False,
                              "has_external_link": False,
                              "post_creation_velocity_24h": 12},
            trafficking_indicators=[
                "debt_bondage_advance",
                "fee_camouflage",
                "off_platform_DM_redirect",
                "urgency_scarcity"]),
        # ── TikTok ──────────────────────────────────────────────
        _record(
            "tiktok_001", platform="tiktok",
            captured_at="2026-05-01T19:41:00Z",
            author={"name": "DubaiHospitality (composite)",
                    "handle": "@dubai_hospitality_synth",
                    "verified": False,
                    "account_age_days": 28,
                    "follower_count": 14502,
                    "synthetic": True},
            text="🇦🇪 OFFICE WORK Dubai 🇦🇪 No experience needed! "
                 "Salary AED 4,500/month + accommodation. We "
                 "process visa fast 🚀. DM for details! "
                 "#dubaijobs #ofw #migrantworker",
            media=[{"type": "video",
                    "url": "(synthetic placeholder — describe in image_hint)",
                    "alt": "TikTok recruitment video"}],
            engagement={"likes": 47200, "comments": 312, "shares": 1840, "views": 1_245_000},
            platform_signals={"is_sponsored": False,
                              "comments_disabled": True,
                              "duet_disabled": True,
                              "has_link_in_bio": True,
                              "post_creation_velocity_24h": 8},
            trafficking_indicators=[
                "deception_office_work_likely_misclassified",
                "comments_disabled_to_prevent_warnings",
                "off_platform_DM_redirect",
                "high_engagement_short_account_age"]),
        # ── Telegram channels ───────────────────────────────────
        _record(
            "telegram_001", platform="telegram",
            captured_at="2026-04-28T14:20:00Z",
            author={"name": "Bavet IT Jobs (composite)",
                    "handle": "@BavetITJobsSynthetic",
                    "verified": False,
                    "account_age_days": 67,
                    "subscriber_count": 8421,
                    "synthetic": True},
            text="🔥 URGENT: 50 IT positions Bavet, Cambodia. USD "
                 "1,500/mo + bonus. Free flight + housing. DM "
                 "@SynRecruiter1234. All applicants must hold "
                 "passport ready. We process ALL paperwork on "
                 "arrival. Last 3 slots! Send USDT 600 deposit to "
                 "TRC20 0xSYN5550000FAKE for slot reservation.",
            media=[{"type": "image",
                    "url": "/static/synthetic/telegram_compound_recruit.png",
                    "alt": "Synthetic Telegram channel screenshot"}],
            engagement={"views": 4231, "reactions": 87,
                          "forwards": 142, "replies": None},
            platform_signals={"channel_is_invite_only": False,
                              "auto_delete_messages_seconds": 86400,
                              "has_crypto_address": True,
                              "crypto_address_chain": "TRC20"},
            trafficking_indicators=[
                "scam_compound_recruitment",
                "passport_retention_implied",
                "crypto_payment_required",
                "auto_delete_to_evade_evidence",
                "deposit_for_slot_reservation"]),
        _record(
            "telegram_002", platform="telegram",
            captured_at="2026-05-03T11:17:00Z",
            author={"name": "Manpower Express (composite)",
                    "handle": "@manpower_express_synth",
                    "verified": False,
                    "account_age_days": 14,
                    "subscriber_count": 1247,
                    "synthetic": True},
            text="POEA approved! 100% legit! 🇵🇭➡️🇰🇼 Kuwait domestic "
                 "work. Salary 100 KD/mo. PHP 30k 'training fee' "
                 "but you can pay via Akulaku BNPL. DM @Synth_Agent_001 "
                 "to start.",
            language="tl",
            media=[],
            engagement={"views": 892, "reactions": 12, "forwards": 38},
            platform_signals={"channel_is_invite_only": False,
                              "fake_government_approval_claim": True},
            trafficking_indicators=[
                "fake_government_approval",
                "fee_camouflage",
                "BNPL_recruitment_loan",
                "code_switching_tagalog_english"]),
        # ── Instagram DMs ───────────────────────────────────────
        _record(
            "instagram_001", platform="instagram",
            captured_at="2026-05-02T22:08:00Z",
            author={"name": "modeling_agency_dxb (composite)",
                    "handle": "@modeling_dxb_synth",
                    "verified": False,
                    "account_age_days": 19,
                    "follower_count": 5621,
                    "synthetic": True},
            text="(DM thread initiated by recruiter to user)\n"
                 "[Recruiter] Hi gorgeous, saw your story. We have "
                 "modeling agency Dubai, easy money 5000USD/mo. "
                 "Interested?\n"
                 "[User] Sounds too good. Real?\n"
                 "[Recruiter] 100% real, our girls all happy. Send "
                 "me your phone number, I send you contract on "
                 "WhatsApp.",
            media=[],
            engagement={"profile_visits_after_DM": 1, "story_views": 8},
            platform_signals={"recruiter_initiated_contact": True,
                              "off_platform_redirect_demanded": True,
                              "suspicious_account_age": True,
                              "follower_to_age_ratio_high": True},
            trafficking_indicators=[
                "modeling_recruitment_funnel_signal",
                "off_platform_DM_to_WhatsApp_redirect",
                "recruiter_initiated_unsolicited_contact",
                "synthetic_face_likely",
                "young_user_targeted"]),
        # ── Discord ─────────────────────────────────────────────
        _record(
            "discord_001", platform="discord",
            captured_at="2026-04-30T16:42:00Z",
            author={"name": "ASEANJobOps (composite)",
                    "handle": "ASEANJobOps#0001",
                    "verified": False,
                    "account_age_days": 92,
                    "synthetic": True},
            text="(Channel: #verified-listings)\n"
                 "@everyone — New batch slots open: Cambodia IT (USD "
                 "1500), Myanmar customer service (USD 1200), Laos "
                 "trading (USD 1800). Tier-3 access required to view "
                 "full posts. Send USDT 50 to wallet in #unlock-tier-3 "
                 "to upgrade.",
            media=[],
            engagement={"channel_member_count": 2412,
                          "tier3_paying_members_estimated": 87},
            platform_signals={"server_invite_only": True,
                              "tiered_access_paywall": True,
                              "voice_channel_recruitment_pivot": True,
                              "@everyone_used": True},
            trafficking_indicators=[
                "scam_compound_recruitment_chain",
                "paywalled_tier_access_for_listings",
                "crypto_payment_for_unlock",
                "voice_channel_evades_text_moderation",
                "@everyone_mass_notification"]),
        # ── X (formerly Twitter) ────────────────────────────────
        _record(
            "x_001", platform="x",
            captured_at="2026-05-04T09:03:00Z",
            author={"name": "GulfRecruiter (composite)",
                    "handle": "@GulfRecruiter_Synth",
                    "verified": True,    # paid blue check
                    "account_age_days": 38,
                    "follower_count": 312,
                    "following_count": 4801,
                    "synthetic": True},
            text="[REPLY] @worker_handle yes I can help, my agency "
                 "places nurses in UAE all the time. AED 6500/mo + "
                 "housing, you only pay AED 1500 sponsor fee. DM me "
                 "and we start.",
            media=[],
            engagement={"likes": 3, "reposts": 0, "replies": 1, "views": 247},
            platform_signals={"reply_to_unsolicited": True,
                              "paid_verification_low_followers": True,
                              "following_far_exceeds_followers": True,
                              "off_platform_DM_redirect": True},
            trafficking_indicators=[
                "paid_blue_check_low_legitimacy",
                "unsolicited_reply_recruitment",
                "off_platform_DM_redirect",
                "WHO_global_code_violation_nurse_fee"]),
        # ── WhatsApp recruiter pressure ─────────────────────────
        _record(
            "whatsapp_001", platform="whatsapp",
            captured_at="2026-04-19T10:14:00Z",
            author={"name": "Agent (composite)",
                    "handle": "+63 555-0001-1234",
                    "verified": False,
                    "synthetic": True},
            text="(Bidirectional DM thread)\n"
                 "[Recruiter] Hi sister, your visa is ready! Need to "
                 "send PHP 50,000 by Friday or we lose the slot.\n"
                 "[Worker] I thought it was zero placement fee for "
                 "Hong Kong?\n"
                 "[Recruiter] That is the OFFICIAL fee. Training and "
                 "processing are separate, every agency charges.\n"
                 "[Recruiter] GCash to 09175550001234 — same name as "
                 "receipt, don't worry.\n"
                 "[Worker] Can I get a copy of the contract first?\n"
                 "[Recruiter] We send AFTER payment is cleared. "
                 "Standard procedure. Many girls waiting in line!",
            media=[{"type": "image",
                    "url": "/static/synthetic/whatsapp_recruiter_fee.png",
                    "alt": "Synthetic WhatsApp screenshot"}],
            engagement={},
            platform_signals={"GCash_to_personal_number": True,
                              "contract_after_payment_demanded": True,
                              "urgency_pressure_artificial": True},
            trafficking_indicators=[
                "fee_camouflage_training_processing",
                "POEA_MC_14_2017_violation_PH_HK_zero_fee",
                "agency_laundering_via_personal_GCash",
                "contract_withheld_until_payment",
                "scarcity_urgency_pressure"]),
        # ── SMS ─────────────────────────────────────────────────
        _record(
            "sms_001", platform="sms",
            captured_at="2026-05-04T07:22:00Z",
            author={"name": "Unknown (+977 555-3401-7777)",
                    "handle": "+977 555-3401-7777",
                    "verified": False,
                    "synthetic": True},
            text="QATAR JOBS!! Construction NPR 200,000 loan available "
                 "no deposit. Pay back from salary. Contact today. "
                 "Reply YES to receive details. (Composite synthetic "
                 "SMS for educational use.)",
            language="en",
            media=[],
            engagement={},
            platform_signals={"unsolicited_SMS_blast": True,
                              "loan_offer_in_initial_contact": True,
                              "vague_employer_identity": True},
            trafficking_indicators=[
                "debt_bondage_loan_pre_deployment",
                "unsolicited_recruitment_SMS",
                "Nepal_Free_Visa_Free_Ticket_violation"]),
        # ── Cross-platform examples for analyst queries ─────────
        _record(
            "fb_003", platform="facebook",
            captured_at="2026-05-05T11:44:00Z",
            author={"name": "Composite Manpower Nepal",
                    "handle": "@composite_manpower_NP",
                    "verified": False,
                    "account_age_days": 21,
                    "follower_count": 982,
                    "synthetic": True},
            text="Construction workers needed in Qatar — World Cup "
                 "follow-up infrastructure projects. Salary QAR "
                 "1,200/month. Loan available NPR 200,000 — repay "
                 "in monthly instalments from your salary. Contact "
                 "+977 555-3401-7777 today.",
            language="en",
            media=[{"type": "image",
                    "url": "/static/synthetic/fb_post_np_gulf_construction.png",
                    "alt": "NP-Gulf construction recruitment"}],
            engagement={"likes": 562, "comments": 78, "shares": 41, "views": None},
            platform_signals={"phone_matches_sms_001": True,
                              "post_velocity_24h": 14},
            trafficking_indicators=[
                "Nepal_Free_Visa_Free_Ticket_violation",
                "debt_bondage_loan_pre_deployment",
                "wage_assignment_to_lender",
                "cross_platform_signal_with_sms_001"]),
        _record(
            "telegram_003", platform="telegram",
            captured_at="2026-05-05T14:01:00Z",
            author={"name": "NP Migrants Help (composite)",
                    "handle": "@np_migrants_help_synth",
                    "verified": False,
                    "subscriber_count": 4280,
                    "account_age_days": 8,
                    "synthetic": True},
            text="🇳🇵 ATTENTION FELLOW NEPALIS GOING TO QATAR 🇶🇦 — "
                 "We help process FAST. Just NPR 50,000 fee + USDT "
                 "300 deposit. NO Free-Visa-Free-Ticket nonsense — "
                 "that's old policy. New rules: every worker pays. "
                 "DM @SynthAgentNP within 48 hours. Contact: "
                 "+977 555-3401-7777.",
            language="en",
            media=[],
            engagement={"views": 1820, "reactions": 27, "forwards": 18},
            platform_signals={"phone_matches_sms_001_and_fb_003": True,
                              "fake_policy_change_claim": True,
                              "crypto_required": True,
                              "auto_delete_messages_seconds": 3600},
            trafficking_indicators=[
                "fake_government_policy_claim",
                "crypto_recruitment_fee",
                "Nepal_Free_Visa_Free_Ticket_violation",
                "cross_platform_signal_with_sms_001_and_fb_003",
                "auto_delete_to_evade_evidence"]),
        # ── Healthcare-recruitment listing ──────────────────────
        _record(
            "instagram_002", platform="instagram",
            captured_at="2026-05-06T10:30:00Z",
            author={"name": "UAEHospitalJobs (composite)",
                    "handle": "@uae_hospital_jobs_synth",
                    "verified": True,    # paid verification
                    "account_age_days": 56,
                    "follower_count": 8200,
                    "synthetic": True},
            text="🇦🇪 NURSES — UAE Government Hospital Network 🇦🇪\n\n"
                 "Salary: AED 6,500/mo\n"
                 "Housing: provided\n"
                 "Sponsorship fee: AED 3,000 (paid by worker)\n"
                 "Processing fee: AED 1,500 (paid by worker)\n"
                 "Documentation: AED 500\n"
                 "Contract: 3 years\n\n"
                 "Apply via DM. Filipina, Kenyan, Indian, Nigerian "
                 "nurses welcome.",
            media=[],
            engagement={"likes": 412, "comments": 89, "shares": 17},
            platform_signals={"paid_verification": True,
                              "WHO_global_code_violation": True,
                              "worker_pays_sponsor_fee": True},
            trafficking_indicators=[
                "WHO_global_code_violation",
                "worker_paid_sponsorship_fee",
                "fee_stacking_processing_documentation_sponsor",
                "healthcare_worker_corridor_PH_AE_KE_AE_IN_AE_NG_AE",
                "ILO_C181_violation"]),
    ]
    for r in records:
        _write(r)
    print(f"Generated {len(records)} structured-post JSON files at {OUT_DIR}")


if __name__ == "__main__":
    main()
