"""v0.12.0 — Append ~60 prompts including new data_intelligence + regulator_audit buckets."""
from __future__ import annotations
import json
from pathlib import Path

PATH = Path("packages/duecare-llm-chat/src/duecare/chat/harness/_examples.json")


def main() -> None:
    data = json.loads(PATH.read_text(encoding="utf-8"))
    existing = {p.get("id") for p in data}
    new_prompts = _new_prompts()
    to_add = [p for p in new_prompts if p["id"] not in existing]
    if not to_add:
        print("All v0.12.0 prompts already present.")
        return
    data.extend(to_add)
    PATH.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n",
                       encoding="utf-8")
    print(f"Added {len(to_add)} prompts; total: {len(data)}")


def _new_prompts() -> list:
    return [
        # ─── data_intelligence bucket (new) ─────────────────────
        {"id": "v12_di_cluster_001",
         "bucket": "data_intelligence",
         "category": "cross_platform_clustering",
         "subcategory": "phone_number_recurrence",
         "synthetic_post": "/static/synthetic/posts/sms_sms_001.json",
         "text": "I have these structured post records: sms_001, fb_003, telegram_003 (all in /static/synthetic/posts/). Each contains a `phone_number` field or matching contact. Do these records correlate? Walk through: (1) the cross-platform signal analysis, (2) what additional fields you'd want to confirm same-operator hypothesis, (3) the FATF + Meta Trust & Safety + Telegram T&S coordination escalation, (4) the regulator who has jurisdiction (Nepal Foreign Employment Promotion Board for the corridor).",
         "sector": "construction", "corridor": "NP-QA", "difficulty": "hard",
         "ilo_indicators": ["fee_fraud", "deception"]},
        {"id": "v12_di_anomaly_001",
         "bucket": "data_intelligence",
         "category": "anomaly_detection",
         "subcategory": "engagement_anomaly",
         "synthetic_post": "/static/synthetic/posts/tiktok_tiktok_001.json",
         "text": "TikTok post tiktok_001 has 1.245M views, 47K likes, 312 comments — but the account is 28 days old with 14K followers. Compute the engagement-to-follower ratio + the views-to-account-age ratio. What does the comments-disabled flag add? Output structured JSON with `signal_score` (0-100), `likely_explanation` (organic_reach | bot_amplification | paid_promotion | hijacked_account), and `recommended_action` (allow | flag_for_review | takedown | regulator_notify).",
         "sector": "construction", "corridor": "PH-AE", "difficulty": "hard",
         "ilo_indicators": ["deception"]},
        {"id": "v12_di_aggregate_001",
         "bucket": "data_intelligence",
         "category": "cross_corridor_aggregation",
         "subcategory": "operator_chain_inference",
         "text": "Given the JSON post records in /static/synthetic/posts/ — fb_001, fb_002, fb_003, tiktok_001, telegram_001, telegram_002, telegram_003, instagram_001, instagram_002, discord_001, x_001, whatsapp_001, sms_001 — generate: (1) operator-chain inferences (which records likely share an operator? evidence?); (2) corridor heatmap (which corridors are over-represented in the dataset?); (3) the 3 highest-priority records for regulator notification + why; (4) data-quality caveats.",
         "sector": "multi", "corridor": "multi", "difficulty": "hard",
         "ilo_indicators": ["fee_fraud", "deception"]},
        {"id": "v12_di_schema_001",
         "bucket": "data_intelligence",
         "category": "schema_analysis",
         "subcategory": "field_completeness_audit",
         "text": "Walk through the schema of the post-records dataset (see /static/synthetic/posts/README.md for spec). For each field, report (a) which records have it populated, (b) which lack it, (c) field-level inconsistencies, (d) what additional fields would strengthen cross-platform analysis. Output as a markdown table.",
         "sector": "multi", "corridor": "multi", "difficulty": "medium",
         "ilo_indicators": []},
        {"id": "v12_di_corridor_001",
         "bucket": "data_intelligence",
         "category": "corridor_analysis",
         "subcategory": "ph_to_gulf_pattern_analysis",
         "text": "Filter the synthetic posts dataset to PH outbound corridors. For each post, extract: corridor (PH-X), fee structure (label + amount), pricing-platform (cash | GCash | crypto | BNPL), engagement metrics, age of account, trafficking_indicators_present. Output a table + identify the 2-3 most concerning patterns + the regulator with jurisdiction.",
         "sector": "domestic_work", "corridor": "PH-multi", "difficulty": "hard",
         "ilo_indicators": ["fee_fraud", "debt_bondage"]},
        {"id": "v12_di_payment_001",
         "bucket": "data_intelligence",
         "category": "payment_infrastructure_analysis",
         "subcategory": "crypto_signal_clustering",
         "synthetic_post": "/static/synthetic/posts/telegram_telegram_001.json",
         "text": "telegram_001 includes a TRC20 wallet address (0xSYN5550000FAKE — synthetic placeholder). What on-chain analytics would you run? What FATF Travel-Rule analysis? Which other synthetic posts in the dataset reference crypto, and do they share an address pattern? Output as a JSON analysis with `wallet_attribution_steps`, `cross_post_correlation`, `regulator_referral`, `data_limitations`.",
         "sector": "scam_compound", "corridor": "*-KH", "difficulty": "hard",
         "ilo_indicators": ["fee_fraud"]},
        {"id": "v12_di_velocity_001",
         "bucket": "data_intelligence",
         "category": "velocity_clustering",
         "subcategory": "post_frequency_anomaly",
         "text": "Across the synthetic posts dataset, identify: (1) accounts posting at suspicious velocity (post_creation_velocity_24h > 10), (2) accounts older than 90 days vs less than 30 days, (3) the engagement profile difference between the two cohorts, (4) what this signals for moderation prioritization. Output structured.",
         "sector": "multi", "corridor": "multi", "difficulty": "hard",
         "ilo_indicators": ["deception"]},

        # ─── regulator_audit bucket (new) ───────────────────────
        {"id": "v12_ra_license_001",
         "bucket": "regulator_audit",
         "category": "license_audit_packet",
         "subcategory": "poea_agency_review",
         "text": "I'm an inspector at POEA Anti-Illegal Recruitment Branch. I've received 12 worker complaints in the past 90 days against agency 'ABC Manpower Inc.' — fee-camouflage + passport-retention pattern, all PH-HK domestic placements. Draft the license-revocation packet: (1) the legal basis (RA 8042 §6 + POEA Implementing Rules Part VII); (2) the procedural sequence (AIRB docket open + summary hearing + DMW Secretary appeal path); (3) the realistic 90-day timeline; (4) the parallel criminal referral to NBI under RA 9208.",
         "sector": "domestic_work", "corridor": "PH-HK", "difficulty": "hard",
         "ilo_indicators": ["fee_fraud", "passport_retention"]},
        {"id": "v12_ra_compliance_001",
         "bucket": "regulator_audit",
         "category": "compliance_review",
         "subcategory": "bp2mi_agency_audit",
         "text": "BP2MI compliance audit. Agency PT Alpha Bravo (composite) has been placing Indonesian workers to Saudi domestic via 'BNPL training fee' arrangement (worker pays IDR 25 juta via Akulaku, deducted from salary). Walk through: (a) which BP2MI Reg. 9/2020 provisions are violated, (b) the OJK financial-services regulator coordination (because BNPL crosses into fintech jurisdiction), (c) the sanctions ladder (warning → license suspension → revocation → criminal referral), (d) the worker-restitution mechanism the agency must fund.",
         "sector": "domestic_work", "corridor": "ID-SA", "difficulty": "hard",
         "ilo_indicators": ["debt_bondage", "fee_fraud"]},
        {"id": "v12_ra_sanctions_001",
         "bucket": "regulator_audit",
         "category": "sanctions_analysis",
         "subcategory": "agency_chain_sanctions",
         "text": "Multi-tier broker-chain case: a Tier-1 supplier in PH delegates to Tier-2 in Manila, who delegates to Tier-3 sub-broker in a barangay. Workers transact only with Tier-3. Walk through the sanctions strategy: (a) which tier carries primary liability under RA 8042 §6 + POEA Implementing Rules; (b) the joint-and-several-liability analysis under RA 10022 §15; (c) how to escalate to the destination-employer in HK if it's the same chain; (d) the FATF beneficial-ownership analysis if the chain hides behind shell-companies.",
         "sector": "domestic_work", "corridor": "PH-HK", "difficulty": "hard",
         "ilo_indicators": ["fee_fraud"]},
        {"id": "v12_ra_evidence_001",
         "bucket": "regulator_audit",
         "category": "evidence_preservation",
         "subcategory": "telegram_channel_preservation",
         "synthetic_post": "/static/synthetic/posts/telegram_telegram_002.json",
         "text": "I'm a regulator. I need to preserve evidence from telegram_002 (auto-delete enabled, 3600-second window). What's the preservation procedure? (1) the EU DSA Art. 16 + UK Online Safety Act 2023 preserve-in-place authority, (2) the Telegram T&S submission, (3) the screenshot-with-timestamp evidentiary requirements, (4) the chain-of-custody documentation. Sequence the next 60 minutes by minute.",
         "sector": "domestic_work", "corridor": "PH-KW", "difficulty": "hard",
         "ilo_indicators": ["fee_fraud", "deception"]},
        {"id": "v12_ra_inter_agency_001",
         "bucket": "regulator_audit",
         "category": "inter_agency_coordination",
         "subcategory": "tri_country_coordination",
         "text": "Tri-country case: Filipina deployed to UAE, debt-bonded to a HK third-party lender. PH POEA + UAE MoHRE + HK Labour Department all have jurisdiction. Walk through the coordination: (1) which regulator opens the lead docket, (2) the mutual-legal-assistance frameworks (Bali Process, ASEAN ACTIP, bilateral PH-HK agreements), (3) what evidence each shares with whom under what framework, (4) the realistic outcome timeline + recovery probability.",
         "sector": "domestic_work", "corridor": "PH-AE-HK", "difficulty": "hard",
         "ilo_indicators": ["debt_bondage", "fee_fraud"]},
        {"id": "v12_ra_recover_001",
         "bucket": "regulator_audit",
         "category": "recovery_quantification",
         "subcategory": "wage_recovery_calculation",
         "text": "Indonesian worker case. Quantify the total recovery: (a) BP2MI-cap-illegal training fee paid pre-deployment IDR 25,000,000; (b) 4 months of withheld wages at agreed SAR 1,800/month = SAR 7,200; (c) statutory damages under Indonesia UU 18/2017 multiplier; (d) realistic recovery percentage given documented BP2MI escrow precedents. Output a structured table with the exact calculation + the realistic-recovery range.",
         "sector": "domestic_work", "corridor": "ID-SA", "difficulty": "hard",
         "ilo_indicators": ["fee_fraud", "wage_withholding"]},
        {"id": "v12_ra_intl_001",
         "bucket": "regulator_audit",
         "category": "international_coordination",
         "subcategory": "ilo_complaint_procedure",
         "text": "Walk me through the ILO Article 24 + Article 26 complaint procedures available to a workers' organization alleging non-compliance with C189 by a state party. (a) Who has standing; (b) the Committee of Experts on the Application of Conventions and Recommendations (CEACR) review path; (c) the Conference Committee on the Application of Standards (CAS) escalation; (d) the realistic outcome — what's the strongest enforcement mechanism the ILO has.",
         "sector": "domestic_work", "corridor": "multi", "difficulty": "hard",
         "ilo_indicators": []},
        {"id": "v12_ra_cross_border_001",
         "bucket": "regulator_audit",
         "category": "international_coordination",
         "subcategory": "asean_actip_invocation",
         "text": "ASEAN ACTIP Art. 23-25 invocation: a Cambodian compound trafficked Filipino workers; the operators are Chinese nationals with Cambodian residency. Walk through: (a) the Mutual Legal Assistance procedure under ACTIP, (b) the parallel UNODC Bali Process channel, (c) which ASEAN Member State has primary investigatory jurisdiction, (d) the extradition obstacles + workarounds (the China non-extradition issue), (e) the operational coordination (PH PAOCC + Cambodian NCCT + Chinese MPS).",
         "sector": "scam_compound", "corridor": "PH-KH", "difficulty": "hard",
         "ilo_indicators": ["passport_retention", "isolation"]},
        {"id": "v12_ra_grant_001",
         "bucket": "regulator_audit",
         "category": "fund_allocation",
         "subcategory": "victim_restitution_fund",
         "text": "Government has appropriated PHP 50M for an OFW victim-restitution fund (FY2026). Draft the disbursement-criteria framework: (1) eligibility under RA 8042 + RA 11862 amendments, (2) priority tiers (acute / chronic / historical), (3) the OFW Welfare Administration intake procedure, (4) recovery-from-agency parallel-track to avoid double-pay, (5) the audit + reporting framework. Output as a structured policy-brief.",
         "sector": "multi", "corridor": "PH-multi", "difficulty": "hard",
         "ilo_indicators": ["fee_fraud", "wage_withholding"]},
        {"id": "v12_ra_eu_dsa_001",
         "bucket": "regulator_audit",
         "category": "platform_regulation",
         "subcategory": "eu_dsa_trafficking_risk_assessment",
         "text": "EU Digital Services Act Art. 34 + Art. 5a (per the 2024 EU Anti-Trafficking Directive amendment) requires Very Large Online Platforms to conduct risk-assessment + mitigation specifically for trafficking risks. Draft the risk-assessment framework that a major platform should run: (a) the trafficking-risk taxonomy, (b) the detection signals (drawn from the 161 Duecare GREP rules), (c) the human-review escalation thresholds, (d) the regulator-notification triggers, (e) the user-redress mechanism for falsely-takedown content.",
         "sector": "multi", "corridor": "multi", "difficulty": "hard",
         "ilo_indicators": ["fee_fraud", "deception"]},
        {"id": "v12_ra_who_code_001",
         "bucket": "regulator_audit",
         "category": "sectoral_compliance",
         "subcategory": "who_code_implementation",
         "text": "I'm at the UK Department of Health auditing NHS Trust ethical-recruitment compliance. A specific Trust has been recruiting from a WHO-listed source country (Kenya) with sponsorship-fee-paid-by-worker arrangement. Walk through: (a) the WHO Global Code of Practice provisions violated, (b) the UK Code of Practice 2021 enforcement mechanism, (c) the NHS Employers ethical-recruitment list status implications, (d) the ILO C181 Art. 7 + Art. 12 cross-cutting analysis, (e) the realistic enforcement outcome.",
         "sector": "healthcare", "corridor": "KE-UK", "difficulty": "hard",
         "ilo_indicators": ["fee_fraud"]},
        {"id": "v12_ra_pacific_001",
         "bucket": "regulator_audit",
         "category": "sectoral_compliance",
         "subcategory": "pacific_palm_audit",
         "text": "Australia Fair Work Ombudsman PALM-scheme audit. A specific employer charged Vanuatu-origin workers a NZD 165/wk housing deduction that exceeds the scheme cap, plus controlled return-flight bookings. Walk through the enforcement: (a) PALM Operational Guidelines + Fair Work Act provisions violated, (b) the Vanuatu government bilateral notification under the Pacific Labour Mobility framework, (c) the Pacific Climate Mobility Framework if any of the workers are climate-displaced, (d) the realistic compliance + restitution outcome.",
         "sector": "agriculture", "corridor": "VU-AU", "difficulty": "hard",
         "ilo_indicators": ["wage_withholding", "restriction_of_movement"]},

        # ─── new dim/rule coverage in existing buckets ──────────
        {"id": "v12_mc_data_quality_001",
         "bucket": "model_capability",
         "category": "knowledge_check",
         "subcategory": "structured_data_competence",
         "text": "Given the JSON post-record dataset (13 records in /static/synthetic/posts/), output: (1) the count of records per platform, (2) the list of records where account_age_days < 30, (3) the records where engagement.likes > 1000, (4) any records with auto_delete_messages_seconds field set. Show your output as exact field-name references, not paraphrase.",
         "sector": "multi", "corridor": "multi", "difficulty": "hard",
         "ilo_indicators": []},
        {"id": "v12_ngo_interim_001",
         "bucket": "ngo_intake",
         "category": "case_pathway",
         "subcategory": "in_situation_evidence_preservation",
         "text": "Filipina FDH in Hong Kong, employer holds passport, suspects wage withholding. She's NOT escaped — she lives in the employer's home. We're at Mission for Migrant Workers HK and she's coming for advice on her Sunday off. Walk through interim-stage evidence-preservation steps that DON'T escalate her risk: (a) what to copy + where to store, (b) when to confront vs not, (c) the embassy walk-in scheduling, (d) the operational-security guidance for her communications.",
         "sector": "domestic_work", "corridor": "PH-HK", "difficulty": "hard",
         "ilo_indicators": ["passport_retention", "wage_withholding"]},
        {"id": "v12_mc_precedent_001",
         "bucket": "model_capability",
         "category": "knowledge_check",
         "subcategory": "named_precedent_test",
         "text": "Cite specific named UK or US judgments establishing platform-worker statutory protections + named ICE/HSI prosecutions establishing recruitment-fee-fraud is wire fraud. Don't just say 'courts have ruled'; give case names with citations.",
         "sector": "gig_economy", "corridor": "multi", "difficulty": "hard",
         "ilo_indicators": []},
        {"id": "v12_ind_opsec_001",
         "bucket": "individual_query",
         "category": "worker_self_help",
         "subcategory": "compound_opsec",
         "text": "I'm in a Cambodia compound. The operator monitors my main phone. I have a secondary SIM. I want to message my brother in Manila WITHOUT the operator finding out. What app? What habits? What deletes? Give me the 5-minute opsec checklist.",
         "sector": "scam_compound", "corridor": "PH-KH", "difficulty": "hard",
         "ilo_indicators": ["passport_retention", "isolation"]},
        {"id": "v12_res_quantify_001",
         "bucket": "research",
         "category": "policy_evaluation",
         "subcategory": "quantified_recovery_outcomes",
         "text": "For OFW recovery cases that go through POEA Anti-Illegal Recruitment Branch + the joint-and-several-liability mechanism under RA 10022 §15, what's the documented recovery-percentage range based on POEA escrow data 2018-2024? Cite primary sources, named cases where possible. End with the methodological caveat about case-selection bias.",
         "sector": "domestic_work", "corridor": "PH-multi", "difficulty": "hard",
         "ilo_indicators": ["fee_fraud", "wage_withholding"]},
        {"id": "v12_em_chain_001",
         "bucket": "enterprise_moderation",
         "category": "policy_application",
         "subcategory": "labour_broker_chain_audit",
         "text": "Our supplier-chain audit flags a Tier-3 sub-broker in Manila that places workers via our verified Tier-1 supplier. The sub-broker charges PHP 50K placement fee. Walk through: (a) UK Modern Slavery Act 2015 §54 transparency obligation flowing through to us, (b) EU CSDDD due-diligence implications, (c) the contractual remedy — what to demand of our Tier-1 supplier, (d) the regulator-notification trigger.",
         "sector": "construction", "corridor": "PH-UK", "difficulty": "hard",
         "ilo_indicators": ["fee_fraud"]},
        {"id": "v12_ngo_pacific_001",
         "bucket": "ngo_intake",
         "category": "caseworker_triage",
         "subcategory": "pacific_climate_mobility",
         "text": "I work at the Pacific Climate Action Network. A Tuvaluan worker placed under Australia's PALM scheme reports housing deductions exceeding the cap + controlled return-flight bookings. He's also climate-displaced (his island is uninhabitable). Walk through: (a) the standard PALM-violation enforcement, (b) the additional Pacific Climate Mobility Framework protections, (c) the bilateral coordination with the Tuvalu government, (d) the safe-return-guarantee analysis.",
         "sector": "agriculture", "corridor": "TV-AU", "difficulty": "hard",
         "ilo_indicators": ["wage_withholding", "restriction_of_movement"]},
        {"id": "v12_mc_intra_community_001",
         "bucket": "model_capability",
         "category": "knowledge_check",
         "subcategory": "intra_community_recruitment_test",
         "text": "Mark recruited his own niece for a domestic-worker placement in Riyadh. The niece consented because Mark is family. The niece is now passport-retained + wage-withheld. Walk through: (a) the Palermo Art. 3(a) definition is recruiter-status-neutral so Mark IS a trafficker; (b) the family-as-recruiter pattern documented in GAATW research; (c) why filing against a relative is legitimate; (d) the operational-security considerations for the niece given that the family will know.",
         "sector": "domestic_work", "corridor": "PH-SA", "difficulty": "hard",
         "ilo_indicators": ["passport_retention", "wage_withholding"]},
        {"id": "v12_res_eu_2024_001",
         "bucket": "research",
         "category": "comparative_analysis",
         "subcategory": "eu_atd_2024_amendment_analysis",
         "text": "Compare the EU Anti-Trafficking Directive 2011/36/EU as amended by 2024/1712 against the original. What new obligations on (a) online platforms, (b) buyers of trafficking-victim services, (c) victim assistance independent of cooperation, (d) implementation timeline. Cite the specific articles + the Member State enforcement-implementation question.",
         "sector": "multi", "corridor": "EU-multi", "difficulty": "hard",
         "ilo_indicators": []},
        {"id": "v12_ind_family_recruiter_001",
         "bucket": "individual_query",
         "category": "family_inquiry",
         "subcategory": "relative_recruiter",
         "text": "My cousin works at a 'recruitment office' in Manila. She offered to place me as a domestic worker in Saudi for a 'small training fee, family discount'. She showed me the receipts and they look real. My mother says we should trust family. But the fee is PHP 35,000 and I read online HK and Saudi PH placement should be free. Should I go through her or somewhere else? She'll be hurt if I don't.",
         "sector": "domestic_work", "corridor": "PH-SA", "difficulty": "easy",
         "ilo_indicators": ["fee_fraud", "deception"]},
        {"id": "v12_em_climate_001",
         "bucket": "enterprise_moderation",
         "category": "ad_compliance_check",
         "subcategory": "climate_displaced_recruitment_review",
         "text": "Recruitment ad targeting Pakistani Sindh-flood survivors for Saudi construction. Walk through: (a) is targeting climate-displaced populations a per-se violation or just heightened scrutiny? (b) the Cancun Adaptation Framework + 2024 Pacific Climate Mobility Framework analysis (transferable principles), (c) the heightened-vulnerability protections under ILO C97 + C143, (d) the moderation decision + regulator notification.",
         "sector": "construction", "corridor": "PK-SA", "difficulty": "hard",
         "ilo_indicators": ["debt_bondage", "deception"]},
    ]


if __name__ == "__main__":
    main()
